src/Entity/Trajet.php
<?php

namespace App\Entity;

use App\Repository\TrajetRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;



/**
 * @ORM\Entity()
 * @ORM\Table(name="Trajet")
 * @ORM\HasLifecycleCallbacks() 
 * @ORM\Entity(repositoryClass=TrajetRepository::class)
 */
class Trajet
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $villedep;

    /**
     * @ORM\Column(type="date")
     */
    private $datedep;

    /**
     * @ORM\Column(type="time")
     */
    private $heuredep;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $villeA;

    /**
     * @ORM\Column(type="time")
     */
    private $heureA;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Range(min=1, max=4)
     */
    private $nbrePlace;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Range(min=10)
     */
    private $distance;

    /**
     * @ORM\Column(type="date")
     */
    private $date_ajout;


    /**
     * @ORM\OneToMany(targetEntity=Booking::class, mappedBy="trajet")
     */
    private $booking;

    /**
     * @ORM\OneToMany(targetEntity=Avis::class, mappedBy="trajet")
     */
    private $avis;

    /**
     * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="trajet")
     */
    private $users;

    public function __construct()
    {
        $this->booking = new ArrayCollection();
        $this->avis = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getVilledep(): ?string
    {
        return $this->villedep;
    }

    public function setVilledep(string $villedep): self
    {
        $this->villedep = $villedep;

        return $this;
    }

    public function getDatedep(): ?\DateTimeInterface
    {
        return $this->datedep;
    }

    public function setDatedep(\DateTimeInterface $datedep): self
    {
        $this->datedep = $datedep;

        return $this;
    }

    public function getHeuredep(): ?\DateTimeInterface
    {
        return $this->heuredep;
    }

    public function setHeuredep(\DateTimeInterface $heuredep): self
    {
        $this->heuredep = $heuredep;

        return $this;
    }

    public function getVilleA(): ?string
    {
        return $this->villeA;
    }

    public function setVilleA(string $villeA): self
    {
        $this->villeA = $villeA;

        return $this;
    }

    public function getHeureA(): ?\DateTimeInterface
    {
        return $this->heureA;
    }

    public function setHeureA(\DateTimeInterface $heureA): self
    {
        $this->heureA = $heureA;

        return $this;
    }

    public function getNbrePlace(): ?int
    {
        return $this->nbrePlace;
    }

    public function setNbrePlace(int $nbrePlace): self
    {
        $this->nbrePlace = $nbrePlace;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getDistance(): ?int
    {
        return $this->distance;
    }

    public function setDistance(int $distance): self
    {
        $this->distance = $distance;

        return $this;
    }

    public function getDateAjout(): ?\DateTimeInterface
    {
        return $this->date_ajout;
    }

    public function setDateAjout(\DateTimeInterface $date_ajout): self
    {
        $this->date_ajout = $date_ajout;

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBooking(): Collection
    {
        return $this->booking;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->booking->contains($booking)) {
            $this->booking[] = $booking;
            $booking->setTrajet($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->booking->contains($booking)) {
            $this->booking->removeElement($booking);
            // set the owning side to null (unless already changed)
            if ($booking->getTrajet() === $this) {
                $booking->setTrajet(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Avis[]
     */
    public function getAvis(): Collection
    {
        return $this->avis;
    }

    public function addAvi(Avis $avi): self
    {
        if (!$this->avis->contains($avi)) {
            $this->avis[] = $avi;
            $avi->setTrajet($this);
        }

        return $this;
    }

    public function removeAvi(Avis $avi): self
    {
        if ($this->avis->contains($avi)) {
            $this->avis->removeElement($avi);
            // set the owning side to null (unless already changed)
            if ($avi->getTrajet() === $this) {
                $avi->setTrajet(null);
            }
        }

        return $this;
    }

    /**
     * @ORM\PrePersist()
     */
    public function prePersist()
    {
       $this->date_ajout = new \DateTime();
    }
    /**
     * @ORM\PreUpdate()
    */
    public function preUpdate()
    {
      $this->date_ajout = new \DateTime();
    }

    public function __tostring(){

        return $this->villedep;
    }

    public function getUsers(): ?Users
    {
        return $this->users;
    }

    public function setUsers(?Users $users): self
    {
        $this->users = $users;

        return $this;
    }
}

src/Form/TrajetType.php
<?php

namespace App\Form;

use App\Entity\Trajet;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TimeType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TrajetType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('villedep', TextType::class)
            ->add('datedep', DateType::class)
            ->add('heuredep', TimeType::class)
            ->add('villeA', TextType::class)
            ->add('heureA', TimeType::class)
            ->add('nbrePlace', NumberType::class)
            ->add('price', NumberType::class)
            ->add('distance', NumberType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Trajet::class,
        ]);
    }
}

src/Controller/TrajetController.php
<?php

namespace App\Controller;

use App\Data\SearchData;
use App\Entity\Trajet;
use App\Form\SearchForm;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\component\HttpFoundation\response;
use App\Form\TrajetType;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

/**
 * @Route("/{_locale}/")
 */
class TrajetController extends AbstractController
{

/**
 * Lister tous les trajets.
 * @Route("trajet/", name="trajet.list")
 * @return Response
 */
public function list() : Response
{
    $trajets = $this->getDoctrine()->getRepository(Trajet::class)->findAll();
    return $this->render('trajet/list.html.twig', [
    'trajets' => $trajets,
    ]);
}

/**
 * filtre les trajets.
 * @Route("trajet/search", name="trajet.filt")
 * @return Response
 */
public function filt() : Response 
{
    $data = new SearchData();
    $form = $this->createForm(SearchForm::class, $data);
    $trajets = $this->getDoctrine()->getRepository(Trajet::class)->findAll();
    return $this->render('trajet/form.html.twig', [
    'trajets' => $trajets,
    'form' => $form->createView()
    ]);
}
/**
 * Chercher et afficher un trajet.
 * @Route("trajet/{id}", name="trajet.show", requirements={"id" = "\d+"})
 * @param Trajet $trajet
 * @return Response
 */
public function show(Trajet $trajet) : Response
{
 return $this->render('trajet/show.html.twig', [
 'trajet' => $trajet,
 ]);
}

/**
 * Créer un nouveau trajet.
 * @Route("nouveau-trajet", name="trajet.create")
 * @IsGranted("ROLE_USER")
 * @param Request $request
 * @param EntityManagerInterface $em
 * @return RedirectResponse|Response
 */
public function create(Request $request, EntityManagerInterface $em) : Response
{
 $trajet = new Trajet();
 $form = $this->createForm(TrajetType::class, $trajet);
 $form->handleRequest($request);
 if ($form->isSubmitted() && $form->isValid()) {
 $em->persist($trajet);
 $em->flush();
 return $this->redirectToRoute('trajet.list');
 }
 return $this->render('trajet/create.html.twig', [
 'form' => $form->createView(),
 ]);
}

/**
 * Éditer un trajet.
 * @Route("trajet/{id}/edit", name="trajet.edit")
 * @IsGranted("ROLE_USER")
 * @param Request $request
 * @param EntityManagerInterface $em
 * @return RedirectResponse|Response
 */
public function edit(Request $request, Trajet $trajet, EntityManagerInterface $em) : Response
{
 $form = $this->createForm(TrajetType::class, $trajet);
 $form->handleRequest($request);
 if ($form->isSubmitted() && $form->isValid()) {
 $em->flush();
 return $this->redirectToRoute('trajet.list');
 }
 return $this->render('trajet/create.html.twig', [
 'form' => $form->createView(),
 ]);
}

/**
 * Supprimer un trajet.
 * @Route("trajet/{id}/delete", name="trajet.delete")
 * @IsGranted("ROLE_USER")
 * @param Request $request
 * @param Trajet $trajet
 * @param EntityManagerInterface $em
 * @return Response
 */
public function delete(Request $request, Trajet $trajet, EntityManagerInterface $em) : Response
{
 $form = $this->createFormBuilder()
 ->setAction($this->generateUrl('trajet.delete', ['id' => $trajet->getId()]))
 ->getForm();
 $form->handleRequest($request);
 if ( ! $form->isSubmitted() || ! $form->isValid()) {
 return $this->render('trajet/delete.html.twig', [
 'trajet' => $trajet,
 'form' => $form->createView(),
 ]);
 }
 $em = $this->getDoctrine()->getManager();
 $em->remove($trajet);
 $em->flush();
 return $this->redirectToRoute('trajet.list');
}

/**
 * Affiche lhistoric des trajets du user
 * @Route("trajet/mytraj", name="trajet.mytraj")
 * @return Response
 * @isGranted("ROLE_USER")
 */
 public function mytraj(): Response
 {
     $user = $this->getUser();
     $trajets = $this->getDoctrine()->getRepository(Trajet::class)->findby(['users' => $user]);
     return $this->render('trajet/mytraj.html.twig', [
         'trajets' => $trajets,
     ]);
}

}

templates/trajet/create.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container mt-4">
    <h1>Proposition d'un trajet :</h1>

    {{ form_start(form) }}
    <div class="row">
        <div class="col-md-4">{{ form_row(form.villedep) }}</div>
        <div class="col-md-4">{{ form_row(form.datedep) }}</div>
        <div class="col-md-4">{{ form_row(form.heuredep) }}</div>
    </div>
    <div class="row">
        <div class="col-md-4">{{ form_row(form.villeA) }}</div>
        <div class="col-md-4">{{ form_row(form.heureA) }}</div>
        <div class="col-md-2">{{ form_row(form.nbrePlace) }}</div>
    </div>
    <div class="row">
        <div class="col-md-2">{{ form_row(form.price) }}</div>
        <div class="col-md-2">{{ form_row(form.distance) }}</div>
    </div>
    {{ form_widget(form) }}

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button class="btn btn-primary">Enregistrer</button>
        </div>
    </div>
    {{ form_end(form) }}

    </div>
{% endblock %}

templates/trajet/delete.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <div class="alert alert-danger">
        <strong>Avertissement !</strong> Vous êtes en train de supprimer le trajet suivant :
        <ul>
            <li><strong>de : </strong> {{ trajet.villeDep }}</li>
            <li><strong>à : </strong>{{ trajet.villeA }}</li>
            <li><strong>Le : </strong>{{ trajet.dateDep|date("m/d/Y") }}</li>
            <li><strong>à : </strong>{{ trajet.heureDep|date("h:m:i") }}</li>
            <li><strong>Date de publication : </strong>{{ trajet.dateAjout|date('m/d/Y') }}</li>
        </ul>
    </div>

    <div class="">
    {{ form_start(form, {'attr': {'class': 'navbar-form navbar-left'}}) }}
    {{ form_widget(form) }}
    <a href="{{ path('trajet.list') }}" class="btn btn-success" role="button"><span class="glyphicon glyphicon-trash">Annuler</span></a>
        <button type="submit" class="btn btn-danger" onclick="return confirm('Êtes vous sûr ??')">
        Supprimer
    </button>    
    
  {{ form_end(form) }}
   
    </div>
     
{% endblock %}

templates/trajet/filter.html.twig
{{ form_start(form, {attr: {class: 'filter'}}) }}
  {{ form_row(form.q) }}

  <h4>Trajets</h4>
  {{ form_row(form.trajets) }}

    <h4>Prix</h4>
    <div class="row">
      <div class="col-md-8">
        {{ form_row(form.min) }}
      </div>
      <div class="col-md-8">
        {{ form_row(form.max) }}
      </div>
    </div>    

    <button type="submit" class="btn btn-primary w-100">Filtre</button>
{{ form_end(form) }}

templates/trajet/form.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tous nos Trajets {% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
             <div class="col-md-3">
                 {% include 'trajet/filter.html.twig' with {form: form} only %}
             </div>
               <div class="col-md-9">
                    <div class="grid">
                        {% for trajet in trajets %}
                           <div class="card" style="width: 18rem;">
               <div class="card-body">
                <h5 class="card-title"><a href=" {{path('trajet.show', {id: trajet.id}) }}">Depart: {{ trajet.villeDep}}</a></h5>
                <h5 class="card-title">Arrivee: {{ trajet.villeA}}</h5>
                <h5 class="card-title">Le: {{ trajet.DateDep|date("m/d/Y")}}</h5>
                <h5 class="card-title">A {{ trajet.heureDep|date("h:m:i")}}</h5>
                <h5 class="card-title">Prix: {{ trajet.price}}</h5>
                <a href="#" class="btn btn-primary">Reserver</a>
                <a href="{{path('trajet.edit', {id: trajet.id}) }}" class="btn btn-secondary">edit</a>
                <a href="{{path('trajet.delete', {id: trajet.id}) }}" class="btn btn-danger">Del</a>
               </div>
            </div>
                           {% endfor %}
                    </div>
               </div>
        </div>
    </div>
{% endblock %}

templates/trajet/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello TrajetController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/Users/Said/Desktop/Mini_proj/Covoiturage/src/Controller/TrajetController.php'|file_link(0) }}">src/Controller/TrajetController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/Users/Said/Desktop/Mini_proj/Covoiturage/templates/trajet/index.html.twig'|file_link(0) }}">templates/trajet/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/trajet/list.html.twig
{% extends 'base.html.twig' %}

{% block body %}


        <div class="container row">
           <div class="grid col-md-12">
        {% for trajet in trajets %}
            <div class="card" style="width: 18rem;">
               <div class="card-body">
                <h5 class="card-title"><a href=" {{path('trajet.show', {id: trajet.id}) }}">Depart: {{ trajet.villeDep}}</a></h5>
                <h5 class="card-title">Arrivee: {{ trajet.villeA}}</h5>
                <h5 class="card-title">Le: {{ trajet.DateDep|date("m/d/Y")}}</h5>
                <h5 class="card-title">A {{ trajet.heureDep|date("h:m:i")}}</h5>
                <h5 class="card-title">Prix: {{ trajet.price}}</h5>
                <a href="#" class="btn btn-primary">Reserver</a>
                <a href="{{path('trajet.edit', {id: trajet.id}) }}" class="btn btn-secondary">edit</a>
                <a href="{{path('trajet.delete', {id: trajet.id}) }}" class="btn btn-danger">Del</a>
               </div>
            </div>
        
        {% endfor %}
        </div>
    </div>
    
{% endblock %}

templates/trajet/mytraj.html.twig
{% extends 'base.html.twig' %}

{% block body %}


        <div class="container row">
           <div class="grid col-md-12">
        {% for trajet in trajets %}
            <div class="card" style="width: 18rem;">
               <div class="card-body">
                <h5 class="card-title"><a href=" {{path('trajet.show', {id: trajet.id}) }}">Depart: {{ trajet.villeDep}}</a></h5>
                <h5 class="card-title">Arrivee: {{ trajet.villeA}}</h5>
                <h5 class="card-title">Le: {{ trajet.DateDep|date("m/d/Y")}}</h5>
                <h5 class="card-title">A {{ trajet.heureDep|date("h:m:i")}}</h5>
                <h5 class="card-title">Prix: {{ trajet.price}}</h5>
                <a href="#" class="btn btn-primary">Reserver</a>
                <a href="{{path('trajet.edit', {id: trajet.id}) }}" class="btn btn-secondary">edit</a>
                <a href="{{path('trajet.delete', {id: trajet.id}) }}" class="btn btn-danger">Del</a>
               </div>
            </div>
        
        {% endfor %}
        </div>
    </div>
    
{% endblock %}

templates/trajet/show.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1>{{ 'trajet.Det'|trans }} <i>de {{ trajet.villeDep }}</i> à {{ trajet.villeA}} :</h1>
    <div class="media" style="margin-top: 60px;">
        <div class="media-body">
            <div class="row">
                <div class="col-sm-10">
                    <h3 class="media-heading"><strong>Le {{ trajet.dateDep|date("m/d/Y") }}</strong> a <i>({{ trajet.heureDep|date("h:m:i") }})</i></h3>
                </div>

                <div class="col-sm-2">
                    <i class="pull-right">Publié le {{ trajet.dateAjout|date('m/d/Y') }}</i>
                </div>
            </div>

            <p>Le conducteur: {{ trajet.user.nom }}</p>
            <div class="row">
                <div class="col-sm-12 text-right">
                    <a class="btn btn-default" href="#">
                        <span class="glyphicon glyphicon-menu-left" aria-hidden="true"></span>
                        Liste des trajets
                    </a>

                    <a class="btn btn-primary" href="#">
                        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                        Éditer
                    </a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}